print("Press X to Open the GUI once loaded (Changeable in Settings.)")

wait(1)

print("Made by jahi#7777")

wait(1)

print("initiated HEXAi Lauch")

wait(1)

print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.5)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Finished loading Internal UI")
wait(1)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Finished loading CoreUI")
wait(1)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)

local function gameFreeze(duration)
    local endTime = os.clock() + duration
    while os.clock() < endTime do
    
    end
end

gameFreeze(2)

print("Successfully bypassed Byfron.")
wait(1)

print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)
print("Loading.")
wait(0.25)
print("Loading..")
wait(0.25)
print("Loading...")
wait(0.25)

print("Finished Loading HEXAi API.")
wait(1)
print("Welcome to, HEXAi v1.7.3")
game.Players.LocalPlayer:Kick("Game not Whitelisted. Find the list here: discord.gg/rDCCnFdbb4")
