print("initiated HEXAi Lauch")
print("loading.")
print("loading..")
print("loading...")
print("Finished Loading in 1 ms")
print("Welcome to, HEXAi v1.7.3")
game.Players.LocalPlayer:Kick("Byfron Detected, Error Loading discord.gg/rDCCnFdbb4")
